
version: '2.0'
services:
  json-server:
    image: qyvlik/typicode-json-server:0.17.3
    command:
      - json-server
      - --watch
      - db.json
      - --host
      - 0.0.0.0
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"